AspNetCoreBootstrap4Validation/ViewModels/AjaxValidationListModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreBootstrap4Validation.ViewModels
{
    public class AjaxValidationListModel
    {
        public List<AjaxValidationModel> Items { get; set; }
    }
}

AspNetCoreBootstrap4Validation/ViewModels/AjaxValidationModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreBootstrap4Validation.ViewModels
{
    public class AjaxValidationModel
    {
        public bool IsCool { get; set; }

        public int Age { get; set; } = 18;

        [Required]
        public string Name { get; set; }
    }
}

AspNetCoreBootstrap4Validation/ViewModels/MyComponentModel.cs
namespace AspNetCoreBootstrap4Validation.ViewModels
{
    public class MyComponentModel 
    {
        public StandardValidationModel StandardValidation { get; set; }
        public string ScreenWidth { get; set; }
    }
}

AspNetCoreBootstrap4Validation/ViewModels/RemoteValidationModel.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreBootstrap4Validation.ViewModels
{
    public class RemoteValidationModel
    {
        public bool IsCool { get; set; }

        [Required]
        [Remote(action: "VerifyNameAndAge", controller: "RemoteTest", AdditionalFields = nameof(Name))]
        public int Age { get; set; }

        [Required]
        public string Name { get; set; }
    }
}

AspNetCoreBootstrap4Validation/ViewModels/StandardValidationModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreBootstrap4Validation.ViewModels
{
    public class StandardValidationModel
    {
        public bool IsCool { get; set; }

        [Range(0, 110, ErrorMessage ="outside my validation range..." )]
        public int Age { get; set; }

        [Required(ErrorMessage = "Required error message defined on the model")]
        public string Name { get; set; }
    }
}

AspNetCoreBootstrap4Validation/Controllers/AjaxComplexListController.cs
using Microsoft.AspNetCore.Mvc;
using AspNetCoreBootstrap4Validation.ViewModels;
using System.Collections.Generic;

namespace AspNetCoreBootstrap4Validation.Controllers
{
    public class AjaxComplexListController : Controller
    {
        public IActionResult Index()
        {
            return View(new AjaxValidationListModel {
                Items = new List<AjaxValidationModel> {
                    new AjaxValidationModel(),
                    new AjaxValidationModel()
                }
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(AjaxValidationModel model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_partialComplexAjaxForm", model);
            }

            // the client could validate this, but allowed for testing server errors
            if(model.Name.Length < 3)
            {
                ModelState.AddModelError("name", "Name should be longer than 2 chars");
                return PartialView("_partialComplexAjaxForm", model);
            }

            ModelState.Clear();
            return PartialView("_partialComplexAjaxForm", model);
        }
    }
}

AspNetCoreBootstrap4Validation/Controllers/AjaxTestController.cs
using Microsoft.AspNetCore.Mvc;
using AspNetCoreBootstrap4Validation.ViewModels;

namespace AspNetCoreBootstrap4Validation.Controllers
{
    public class AjaxTestController : Controller
    {
        public IActionResult Index()
        {
            return View(new AjaxValidationModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(AjaxValidationModel model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_partialAjaxForm", model);
            }

            // the client could validate this, but allowed for testing server errors
            if(model.Name.Length < 3)
            {
                ModelState.AddModelError("name", "Name should be longer than 2 chars");
                return PartialView("_partialAjaxForm", model);
            }

            ModelState.Clear();
            return PartialView("_partialAjaxForm");
        }
    }
}

AspNetCoreBootstrap4Validation/Controllers/AjaxWithComponentController.cs
using Microsoft.AspNetCore.Mvc;
using AspNetCoreBootstrap4Validation.ViewModels;

namespace AspNetCoreBootstrap4Validation.Controllers
{
    public class AjaxWithComponentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LoadComponent(MyComponentModel model)
        {
            return ViewComponent("MyComponent", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(StandardValidationModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            return Redirect("Home/Index");
        }

        public IActionResult Playground()
        {
            return View();
        }
    }
}

AspNetCoreBootstrap4Validation/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using AspNetCoreBootstrap4Validation.ViewModels;

namespace AspNetCoreBootstrap4Validation.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(StandardValidationModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            return Redirect("Home/Index");
        }

        public IActionResult Playground()
        {
            return View();
        }
    }
}

AspNetCoreBootstrap4Validation/Controllers/RemoteTestController.cs
using Microsoft.AspNetCore.Mvc;
using AspNetCoreBootstrap4Validation.ViewModels;

namespace AspNetCoreBootstrap4Validation.Controllers
{
    public class RemoteTestController : Controller
    {
        public IActionResult Index()
        {
            return View(new RemoteValidationModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(RemoteValidationModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            return Redirect("RemoteTest/Index");
        }

        [AcceptVerbs("Get", "Post")]
        public IActionResult VerifyNameAndAge(string name, int age)
        {
            if (age > 50)
            {
                return Json(data: $" {name} {age} must be less than 50.");
            }

            return Json(data: true);
        }
    }
}

AspNetCoreBootstrap4Validation/Views/AjaxComplexList/Index.cshtml
@using AspNetCoreBootstrap4Validation.ViewModels
@model AjaxValidationListModel
@{
    ViewData["Title"] = "Ajax Test Page";
}

<h4>Ajax Test</h4>

@foreach (var item in Model.Items)
{
    string guid = Guid.NewGuid().ToString();

    <form asp-action="Index" asp-controller="AjaxComplexList" data-ajax="true" data-ajax-method="POST"
          data-ajax-mode="replace" data-ajax-update="#complex-ajax-@guid">

        <div id="complex-ajax-@guid">
            @await Html.PartialAsync("_partialComplexAjaxForm", item)
        </div>
    </form>
}


@section Scripts  {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}


AspNetCoreBootstrap4Validation/Views/AjaxComplexList/_partialComplexAjaxForm.cshtml
@model AspNetCoreBootstrap4Validation.ViewModels.AjaxValidationModel
@{
    string guid = Guid.NewGuid().ToString();
}

<div asp-validation-summary="All" class="text-danger"></div>

<div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" asp-for="Name" 
      id="AjaxValidationModelName" aria-describedby="nameHelp" placeholder="Enter name"
      oninput="$('#submit-@guid').trigger('submit');">
    <small id="nameHelp" class="form-text text-muted">We'll never share your name ...</small>
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label for="age">Age</label>
    <input type="number" asp-for="Age" 
      class="form-control" id="AjaxValidationModelAge" placeholder="0"
      oninput="$('#submit-@guid').trigger('submit');">
    <span asp-validation-for="Age" class="text-danger"></span>
</div>
<div class="form-check ten_px_bottom">
    @Html.CheckBox("IsCool", Model.IsCool,
        new { onchange = "$('#submit-" + @guid + "').trigger('submit');", @class = "big_checkbox" })
    <label class="form-check-label ten_px_left" >Check the checkbox to send a request</label>
</div>

<button style="display: none" id="submit-@guid" type="submit">Submit</button>

AspNetCoreBootstrap4Validation/Views/AjaxTest/Index.cshtml
@{
    ViewData["Title"] = "Ajax Test Page";
}

<h4>Ajax Test</h4>

<form asp-action="Index" asp-controller="AjaxTest" data-ajax="true" data-ajax-method="POST"
      data-ajax-mode="replace" data-ajax-update="#ajaxresult" >

    <div id="ajaxresult">
        @await Html.PartialAsync("_partialAjaxForm")
    </div>
</form>

@section Scripts  {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}


AspNetCoreBootstrap4Validation/Views/AjaxTest/_partialAjaxForm.cshtml
@model AspNetCoreBootstrap4Validation.ViewModels.AjaxValidationModel 

<div asp-validation-summary="All" class="text-danger"></div>

<div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" asp-for="Name" id="AjaxValidationModelName" aria-describedby="nameHelp" placeholder="Enter name">
    <small id="nameHelp" class="form-text text-muted">We'll never share your name ...</small>
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label for="age">Age</label>
    <input type="number" class="form-control" id="AjaxValidationModelAge" asp-for="Age" placeholder="0">
    <span asp-validation-for="Age" class="text-danger"></span>
</div>
<div class="form-check ten_px_bottom">
    <input type="checkbox" class="form-check-input big_checkbox" asp-for="IsCool" id="AjaxValidationModelIsCool">
    <label class="form-check-label ten_px_left" for="IsCool">IsCool</label>
    <span asp-validation-for="IsCool" class="text-danger"></span>
</div>

<button type="submit" class="btn btn-primary">Submit</button>

AspNetCoreBootstrap4Validation/Views/AjaxWithComponent/Index.cshtml
@model AspNetCoreBootstrap4Validation.ViewModels.StandardValidationModel
@{
    ViewData["Title"] = "Ajax with Component Page";
}
<h4>Ajax with Component View</h4>

@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Xsrf
@functions{
    public string GetAntiXsrfRequestToken()
    {
        return Xsrf.GetAndStoreTokens(Context).RequestToken;
    }
}

<input type="hidden" id="RequestVerificationToken"
       name="RequestVerificationToken" value="@GetAntiXsrfRequestToken()">

<div id="partialComponentResult">
    <h5>change a value to do a component load</h5>

    <text><em>ScreenWidth:</em> ...</text>

    <br />
    <text><em>Name:</em> ...</text><br />
    <text><em>IsCool:</em> ...</text><br />
    <text><em>Age:</em> ...</text><br />
</div>

<hr />

<form id="partialformAjaxWithComponent" onchange="loadComponentView()" method="post" asp-action="Index" asp-controller="AjaxWithComponent">

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" asp-for="Name" id="name" aria-describedby="nameHelp" placeholder="Enter name">
        <small id="nameHelp" class="form-text text-muted">We'll never share your name ...</small>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="age">Age</label>
        <input type="number" class="form-control" id="age" asp-for="Age" placeholder="0">
        <span asp-validation-for="Age" class="text-danger"></span>
    </div>
    <div class="form-check ten_px_bottom">
        <input type="checkbox" class="form-check-input big_checkbox" asp-for="IsCool" id="IsCool">
        <label class="form-check-label ten_px_left" for="IsCool">IsCool</label>
        <span asp-validation-for="IsCool" class="text-danger"></span>
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
</form>


@section Scripts  {
    @await Html.PartialAsync("_ValidationScriptsPartial")

    <script language="javascript">

        function loadComponentView() {

            var paramsFromForm = {};
            $.each($("#partialformAjaxWithComponent").serializeArray(), function (index, value) {
                paramsFromForm[value.name] = paramsFromForm[value.name] ? paramsFromForm[value.name] || value.value : value.value;
            });

            var componentData = {};

            componentData.standardValidation = paramsFromForm;
            componentData.screenWidth = document.documentElement.clientWidth;

            console.log(componentData);

            $.ajax({
                url: window.location.origin + "/AjaxWithComponent/LoadComponent",
                type: "post",
                dataType: "json",
                beforeSend: function (x) {
                    if (x && x.overrideMimeType) {
                        x.overrideMimeType("application/json;charset=UTF-8");
                    };
                    x.setRequestHeader('RequestVerificationToken', document.getElementById('RequestVerificationToken').value);   
                },
                data: componentData,
                complete: function (result) {
                    console.log(result.responseText);
                    $("#partialComponentResult").html(result.responseText);
                }
            });
        };

    </script>
}

AspNetCoreBootstrap4Validation/Views/Home/Index.cshtml
@model AspNetCoreBootstrap4Validation.ViewModels.StandardValidationModel
@{
    ViewData["Title"] = "Home Page";
}
<h4>Standard</h4>

<form method="post" asp-action="Index" asp-controller="Home">

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" asp-for="Name" id="name" aria-describedby="nameHelp" placeholder="Enter name">
        <small id="nameHelp" class="form-text text-muted">We'll never share your name ...</small>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="age">Age</label>
        <input type="number" class="form-control" id="age" asp-for="Age" placeholder="0">
        <span asp-validation-for="Age" class="text-danger"></span>
    </div>
    <div class="form-check ten_px_bottom">
        <input type="checkbox" class="form-check-input big_checkbox" asp-for="IsCool" id="IsCool">
        <label class="form-check-label ten_px_left" for="IsCool">IsCool</label>
        <span asp-validation-for="IsCool" class="text-danger"></span>
    </div>
    

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section Scripts  {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

AspNetCoreBootstrap4Validation/Views/Home/Playground.cshtml
@{
    ViewData["Title"] = "Ajax Test Page";
}
<h4>Ajax Test</h4>

<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
    Tooltip on top
</button>
<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="right" title="Tooltip on right">
    Tooltip on right
</button>
<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="bottom" title="Tooltip on bottom">
    Tooltip on bottom
</button>
<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="left" title="Tooltip on left">
    Tooltip on left
</button>

<button type="button" id="example-popover" class="example-popover btn btn-info" data-toggle="popover" title="Popover title" data-content="And here's some amazing content. It's very engaging. Right?">
    <i class="fas fa-info"></i>
</button>

<i class="fas fa-info example-popover btn btn-info" data-toggle="popover" title="Popover title" data-content="And here's some amazing content. It's very engaging. Right?"></i>

AspNetCoreBootstrap4Validation/Views/RemoteTest/Index.cshtml
@model AspNetCoreBootstrap4Validation.ViewModels.RemoteValidationModel
@{
    ViewData["Title"] = "Remote Test Page";
}

<h4>Remote Test</h4>

<form method="post" asp-action="Index" asp-controller="RemoteTest">

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label for="name" data-toggle="tooltip" data-placement="right" title="Add any name">Name</label>
        <input type="text" class="form-control" asp-for="Name" id="name" aria-describedby="nameHelp" placeholder="Enter name">


        <small id="nameHelp" class="form-text text-muted">We'll never share your name ...</small>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="age" data-toggle="tooltip" data-placement="right" title="remote validation checks that age must be less than 50">Age</label>
        <input type="number" class="form-control" id="age" asp-for="Age" placeholder="0">
        <span asp-validation-for="Age" class="text-danger"></span>
    </div>
    <div class="form-check ten_px_bottom">
        <input type="checkbox" class="form-check-input big_checkbox" asp-for="IsCool" id="IsCool">
        <label class="form-check-label ten_px_left" for="IsCool">IsCool</label>
        <span asp-validation-for="IsCool" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section Scripts  {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

AspNetCoreBootstrap4Validation/Views/Shared/Components/MyComponent/Default.cshtml
@using AspNetCoreBootstrap4Validation.ViewModels
@model MyComponentModel

@{
    ViewData["Title"] = "View Component";
}

<h5>Result from Component:server</h5>

<text><em>ScreenWidth: </em>@Model.ScreenWidth</text>

<br />
<text><em>Name:</em> @Model.StandardValidation.Name</text><br />
<text><em>IsCool:</em> @Model.StandardValidation.IsCool</text><br />
<text><em>Age: </em>@Model.StandardValidation.Age</text><br />

AspNetCoreBootstrap4Validation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ASP.NET Core Bootstrap 4 Validation</title>
    <link rel="stylesheet" href="~/css/vendor.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/fontawesome-free-5.4.1-web/css/all.min.css" asp-append-version="true" />
</head>
<body>
    <nav class="bg-dark mb-4 navbar navbar-dark navbar-expand-md">
        <a asp-controller="Home" asp-action="Index" class="navbar-brand">
            <em>ASP.NET Core Bootstrap 4 Validation</em>
        </a>
        <button aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#topNavbarCollapse" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="topNavbarCollapse">
            <ul class="mr-auto navbar-nav">
                <li>
                    <div class="main-menu">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownLangButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                EXAMPLES
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownLangButton">
                                <a asp-area="" asp-controller="Home" asp-action="Index" class="dropdown-item">Standard</a>

                                <a asp-area="" asp-controller="RemoteTest" asp-action="Index" class="dropdown-item">Remote Test</a>

                                <a asp-area="" asp-controller="AjaxTest" asp-action="Index" class="dropdown-item">Ajax Test</a>

                                <a asp-area="" asp-controller="AjaxComplexList" asp-action="Index" class="dropdown-item">Ajax Complex List Test</a>
                            </div>
                        </div>
                    </div>
                </li>

                <li class="nav-item">
                    <a asp-area="" asp-controller="AjaxWithComponent" asp-action="Index" class="nav-link">Ajax with Component View</a>
                </li>

                <li class="nav-item">
                    <a asp-area="" asp-controller="Home" asp-action="Playground" class="nav-link">Bootstrap 4 Playground</a>
                </li>

                @*<li class="nav-item">
            <a asp-controller="Home" asp-action="Index" class="nav-link">Standard</a>
        </li>
        <li class="nav-item">
            <a asp-controller="RemoteTest" asp-action="Index" class="nav-link">Remote Test</a>
        </li>
        <li class="nav-item">
            <a asp-controller="AjaxTest" asp-action="Index" class="nav-link">Ajax Test</a>
        </li>*@
            </ul>
        </div>
    </nav>



    <div class="container body-content">
        @RenderBody()

    </div>


    <nav class="navbar fixed-bottom navbar-light bg-light">
        <footer>
            <p>&copy; 2021 - ASP.NET Core Bootstrap 4 Validation</p>
        </footer>
    </nav>

    <script src="~/js/vendor.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

AspNetCoreBootstrap4Validation/Views/Shared/_ValidationSummary.cshtml
@if (ViewContext.ModelState.IsValid == false)
{
    <div class="alert alert-danger">
        <strong>Error</strong>
        <div asp-validation-summary="All" class="danger"></div>
    </div>
}